version: "3.9"
services:
  pet-match-frontend:
    build:
      context: ../PetMatchFrontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    links:
      - web
    environment:
      - ../PetMatchFrontend/src/environment/environment.ts   
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: petmatch
    ports:
      - "4000:4000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - network1
networks:
  network1: