version: "3.9"
services:
  pet-match-frontend:
    build:
      context: ../PetMatchFrontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    links:
      - web
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: petmatch
    ports:
      - "4000:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
