@host=http://localhost:4000

POST {{host}}/authentication/register
Content-Type: application/json

{
    "firstName": "Ornella",
    "lastName": "Stirparo",
    "email": "ostirparo@gmail.com",
    "password": "Pwd12345."
}