@host=http://localhost:4000
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJQZXRNYXRjaC5Eb21haW4uVXNlcnMuVmFsdWVPYmplY3RzLlVzZXJJZCIsImdpdmVuX25hbWUiOiJvcm5lbGxhIiwiZmFtaWx5X25hbWUiOiJTdGlycGFybyIsImp0aSI6IjY0MmRlMzA1LTY5NzYtNDdjMS05MzFhLThlOGIyYWFjNDM5OSIsImV4cCI6MTY3NjMxNzQ4OCwiaXNzIjoiUGV0TWF0Y2giLCJhdWQiOiJQZXRNYXRjaCJ9.Xl2DqiDAD0BwfZIDGHdTqwoa82frwYhcCXmtfcApdN4
POST {{host}}/pets
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Buddy",
    "description": "A good dog",
    "url": "https://upload.wikimedia.org/wikipedia/commons/9/94/My_dog.jpg"
}