@host=http://localhost:4000
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJQZXRNYXRjaC5Eb21haW4uVXNlcnMuVmFsdWVPYmplY3RzLlVzZXJJZCIsImdpdmVuX25hbWUiOiJPcm5lbGxhIiwiZmFtaWx5X25hbWUiOiJTdGlycGFybyIsImp0aSI6IjM4NTc2ODRjLTdmN2QtNDYzYy1hNzg1LTE4YmY5MTUzM2JkMyIsImV4cCI6MTY3NjE0MjA1MiwiaXNzIjoiUGV0TWF0Y2giLCJhdWQiOiJQZXRNYXRjaCJ9.86EBBSeD7NLx_2gq3ixOG0yRqG0dGuGvKejK4Ax0_0E
POST {{host}}/pets
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Buddy",
    "description": "A good dog",
    "url": "https://upload.wikimedia.org/wikipedia/commons/9/94/My_dog.jpg"
}