@host=http://localhost:4000
@id=619218e3-666f-46fa-a53b-db3eda55a1a5
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJQZXRNYXRjaC5Eb21haW4uVXNlcnMuVmFsdWVPYmplY3RzLlVzZXJJZCIsImdpdmVuX25hbWUiOiJPcm5lbGxhIiwiZmFtaWx5X25hbWUiOiJTdGlycGFybyIsImp0aSI6ImUzOTUyMTFkLTA1MTEtNDc4Zi1iNzg0LWRmNzA5OWFkZjljOCIsImV4cCI6MTY3NjA0ODQ3MSwiaXNzIjoiUGV0TWF0Y2giLCJhdWQiOiJQZXRNYXRjaCJ9.2ekA2cgIjrgyLr99-fH69LbxjUrDlwzCP1aQFc9z19o
GET  {{host}}/pets
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{host}}/pets/{{id}}
Content-Type: application/json
Authorization: Bearer {{token}}