@host=http://localhost:4000
@id=85152109-b8bf-4b5e-b6a2-98ead33d7c48
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJQZXRNYXRjaC5Eb21haW4uVXNlcnMuVmFsdWVPYmplY3RzLlVzZXJJZCIsImdpdmVuX25hbWUiOiJPcm5lbGxhIiwiZmFtaWx5X25hbWUiOiJTdGlycGFybyIsImp0aSI6ImYwYjNmNzdlLTU1ZjgtNDg3My04NmUzLTIwZTQ3MDdlM2QyNCIsImV4cCI6MTY3NjA0NzE4MCwiaXNzIjoiUGV0TWF0Y2giLCJhdWQiOiJQZXRNYXRjaCJ9.WR6N4me41pQQr2Bf8GxJgNSAJLx3OzJPwX02aMmbO0A
GET  {{host}}/pets
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{host}}/pets/{{id}}
Content-Type: application/json
Authorization: Bearer {{token}}