@host=http://localhost:4000
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJQZXRNYXRjaC5Eb21haW4uVXNlcnMuVmFsdWVPYmplY3RzLlVzZXJJZCIsImdpdmVuX25hbWUiOiJPcm5lbGxhIiwiZmFtaWx5X25hbWUiOiJTdGlycGFybyIsImp0aSI6IjUzOWNhYzFiLTFjMjYtNDIxYy1iN2U4LTQ1ZGMzZTI1NWQ5NSIsImV4cCI6MTY3NjAwMTEwMywiaXNzIjoiUGV0TWF0Y2giLCJhdWQiOiJQZXRNYXRjaCJ9.xML4EUEtEYV6wxCNDjAp7a4gN2w4jOdmarFmMGoutfI
GET  {{host}}/pets
Content-Type: application/json
Authorization: Bearer {{token}}
